version: "3"

services:
  app:
    container_name: learn-storybook
    build: .
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    working_dir: /app
    ports:
      - 3000:3000
    volumes:
      - .:/app:cached
      # - node_modules:/app/node_modules
      # - dist://app/dist
# volumes:
# node_modules: {}
# dist: {}
